CREATE TABLE DISCOUNTS
(
  ID_DISCOUNT          SERIAL NOT NULL ,
  AMOUNT               NUMERIC NULL ,
  DESCRIPTION          VARCHAR(200) NULL ,
  TIME_IN_COMPANY      NUMERIC NULL 
);

CREATE UNIQUE INDEX XPKSALEC ON DISCOUNTS
(ID_DISCOUNT   ASC);

ALTER TABLE DISCOUNTS
  ADD CONSTRAINT  XPKSALEC PRIMARY KEY (ID_DISCOUNT);

CREATE TABLE SALES
(
  ID_TARIFFS           NUMERIC NULL ,
  ID_DISCOUNT          NUMERIC NOT NULL ,
  ID_SALES             NUMERIC NOT NULL 
);

CREATE UNIQUE INDEX XPKSALES ON SALES
(ID_SALES   ASC);

ALTER TABLE SALES
  ADD CONSTRAINT  XPKSALES PRIMARY KEY (ID_SALES);

CREATE TABLE TARIFFS
(
  ID_TARIFFS           NUMERIC NOT NULL ,
  NAME                 VARCHAR(40) NOT NULL ,
  COST                 NUMERIC NULL ,
  DESCRIPTION          VARCHAR(120) NULL ,
  START_SALES          DATE NULL ,
  END_SALES            DATE NULL 
);

CREATE UNIQUE INDEX XPKtariffs ON TARIFFS
(ID_TARIFFS   ASC);

ALTER TABLE TARIFFS
  ADD CONSTRAINT  XPKtariffs PRIMARY KEY (ID_TARIFFS);

ALTER TABLE SALES
  ADD (CONSTRAINT R_3 FOREIGN KEY (ID_TARIFFS) REFERENCES TARIFFS (ID_TARIFFS) ON DELETE SET NULL);

ALTER TABLE SALES
  ADD (CONSTRAINT R_4 FOREIGN KEY (ID_DISCOUNT) REFERENCES DISCOUNTS (ID_DISCOUNT));
