
CREATE TABLE DISCOUNTS
(
	ID_DISCOUNT          NUMBER NOT NULL ,
	AMOUNT               NUMBER NULL ,
	DESCRIPTION          VARCHAR2(200) NULL ,
	TIME_IN_COMPANY      NUMBER NULL 
);

CREATE UNIQUE INDEX XPKSALEC ON DISCOUNTS
(ID_DISCOUNT   ASC);

ALTER TABLE DISCOUNTS
	ADD CONSTRAINT  XPKSALEC PRIMARY KEY (ID_DISCOUNT);

CREATE TABLE SALES
(
	ID_TARIFFS           NUMBER NULL ,
	ID_DISCOUNT          NUMBER NOT NULL ,
	ID_SALES             NUMBER NOT NULL 
);

CREATE UNIQUE INDEX XPKSALES ON SALES
(ID_SALES   ASC);

ALTER TABLE SALES
	ADD CONSTRAINT  XPKSALES PRIMARY KEY (ID_SALES);

CREATE TABLE TARIFFS
(
	ID_TARIFFS           NUMBER NOT NULL ,
	NAME                 VARCHAR2(40) NOT NULL ,
	COST                 NUMBER NULL ,
	DESCRIPTION          VARCHAR2(120) NULL ,
	START_SALES          DATE NULL ,
	END_SALES            DATE NULL 
);

CREATE UNIQUE INDEX XPKtariffs ON TARIFFS
(ID_TARIFFS   ASC);

ALTER TABLE TARIFFS
	ADD CONSTRAINT  XPKtariffs PRIMARY KEY (ID_TARIFFS);

ALTER TABLE SALES
	ADD (CONSTRAINT R_3 FOREIGN KEY (ID_TARIFFS) REFERENCES TARIFFS (ID_TARIFFS) ON DELETE SET NULL);

ALTER TABLE SALES
	ADD (CONSTRAINT R_4 FOREIGN KEY (ID_DISCOUNT) REFERENCES DISCOUNTS (ID_DISCOUNT));