
CREATE TABLE DISCOUNTS
(

  ID_DISCOUNT           INTEGER PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY ,
  AMOUNT                NUMERIC ,
  DESCRIPTION           CHARACTER(200) ,
  TIME_IN_COMPANY       NUMERIC 
);

CREATE UNIQUE INDEX XPKDISCOUNTS ON DISCOUNTS 
(

  ID_DISCOUNT
);


CREATE TABLE TARIFFS
(

  ID_TARIFF             INTEGER PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY ,
  NAME                  CHARACTER(120) ,
  COST                  DECIMAL(13,2) ,
  DESCRIPTION           CHARACTER(200) ,
  START_SALES           DATE ,
  END_SALES             DATE 
);

CREATE UNIQUE INDEX XPKTARIFFS ON TARIFFS 
(

  ID_TARIFF
);

CREATE TABLE SALES
(

  ID_SALES              INTEGER PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY ,
  ID_DISCOUNT           INTEGER ,
  ID_TARIFF             INTEGER ,
  FOREIGN KEY (ID_DISCOUNT) REFERENCES DISCOUNTS (ID_DISCOUNT) ON DELETE CASCADE,
  FOREIGN KEY (ID_TARIFF) REFERENCES TARIFFS (ID_TARIFF) ON DELETE CASCADE
);

CREATE UNIQUE INDEX XPKSALES ON SALES 
(

  ID_SALES
);

INSERT INTO TARIFFS (NAME, COST, DESCRIPTION) VALUES ('standart', 600, 'standart tariff');
INSERT INTO TARIFFS (NAME, COST, DESCRIPTION) VALUES ('standart2', 700, 'standart tariff');
INSERT INTO TARIFFS (NAME, COST, DESCRIPTION) VALUES ('standart3', 800, 'standart tariff');


INSERT INTO DISCOUNTS (AMOUNT, TIME_IN_COMPANY, DESCRIPTION) VALUES (100, 1, 'DESCRIPTION1');
INSERT INTO DISCOUNTS (AMOUNT, TIME_IN_COMPANY, DESCRIPTION) VALUES (200, 2, 'DESCRIPTION2');
INSERT INTO DISCOUNTS (AMOUNT, TIME_IN_COMPANY, DESCRIPTION) VALUES (300, 3, 'DESCRIPTION3');
