
CREATE TABLE DISCOUNTS
(

  ID_DISCOUNT           NUMERIC NOT NULL ,
  AMOUNT                NUMERIC ,
  DESCRIPTION           CHARACTER(200) ,
  TIME_IN_COMPANY       NUMERIC 
);

CREATE UNIQUE INDEX XPKDISCOUNTS ON DISCOUNTS 
(

  ID_DISCOUNT
);

CREATE TABLE SALES
(

  ID_SALES              NUMERIC NOT NULL ,
  ID_DISCOUNT           NUMERIC ,
  ID_TARIFF             NUMERIC 
);

CREATE UNIQUE INDEX XPKSALES ON SALES 
(

  ID_SALES
);

CREATE TABLE TARIFFS
(

  ID_TARIFF             NUMERIC NOT NULL ,
  NAME                  CHARACTER(120) ,
  COST                  DECIMAL(13,2) ,
  DESCRIPTION           CHARACTER(200) ,
  START_SALES           DATE ,
  END_SALES             DATE 
);

CREATE UNIQUE INDEX XPKTARIFFS ON TARIFFS 
(

  ID_TARIFF
);


INSERT INTO TARIFFS (NAME, COST, DESCRIPTION) VALUES ("standart", 600, "standart tariff");
INSERT INTO TARIFFS (NAME, COST, DESCRIPTION) VALUES ("standart2", 700, "standart tariff");
INSERT INTO TARIFFS (NAME, COST, DESCRIPTION) VALUES ("standart3", 800, "standart tariff");


INSERT INTO DISCOUNTS (AMOUNT, TIME_IN_COMPANY, DESCRIPTION) VALUES (100, 1, "DESCRIPTION1");
INSERT INTO DISCOUNTS (AMOUNT, TIME_IN_COMPANY, DESCRIPTION) VALUES (200, 2, "DESCRIPTION2");
INSERT INTO DISCOUNTS (AMOUNT, TIME_IN_COMPANY, DESCRIPTION) VALUES (300, 3, "DESCRIPTION3");
