
CREATE TABLE DISCOUNTS
(
  ID_DISCOUNT           serial PRIMARY KEY NOT NULL ,
  AMOUNT                NUMERIC ,
  DESCRIPTION           CHARACTER(200) ,
  TIME_IN_COMPANY       NUMERIC 
);

CREATE UNIQUE INDEX XPKDISCOUNTS ON DISCOUNTS (  ID_DISCOUNT );

CREATE TABLE TARIFFS
(
  ID_TARIFF             serial PRIMARY KEY NOT NULL ,
  NAME                  CHARACTER(200) ,
  COST                  NUMERIC(13,2) ,
  DESCRIPTION           CHARACTER(200) ,
  START_SALES           DATE ,
  END_SALES             DATE 
);

CREATE UNIQUE INDEX XPKTARIFFS ON TARIFFS (  ID_TARIFF );

CREATE TABLE CUSTOMERS
(
    ID_CLIENT           serial PRIMARY KEY NOT NULL ,
    FIRST_NAME          CHARACTER(50) ,
    LAST_NAME           CHARACTER(50) ,
    MIDDLE_NAME         CHARACTER(50) ,
    PASSPORT_SERIES     NUMERIC(4) ,
    PASSPORT_NUMBER     NUMERIC(6) ,
    DATE_OF_BIRTH       DATE
);

CREATE UNIQUE INDEX XPKCUSTOMERS ON CUSTOMERS (  ID_CLIENT );

CREATE TABLE MOBILE_PHONES
(
    ID_PHONE            serial PRIMARY KEY NOT NULL ,
    MOBILE_PHONE        CHARACTER(20) ,
    ID_CLIENT           INTEGER ,
    STATUS              NUMERIC(1) ,
    FOREIGN KEY (ID_CLIENT) REFERENCES CUSTOMERS (ID_CLIENT) ON DELETE CASCADE
);

CREATE UNIQUE INDEX XPKMOBILE_PHONES ON MOBILE_PHONES (  ID_CLIENT );

CREATE TABLE SALES
(
  ID_SALES              serial PRIMARY KEY NOT NULL ,
  ID_DISCOUNT           INTEGER ,
  ID_TARIFF             INTEGER ,
  FOREIGN KEY (ID_DISCOUNT) REFERENCES DISCOUNTS (ID_DISCOUNT) ON DELETE CASCADE,
  FOREIGN KEY (ID_TARIFF) REFERENCES TARIFFS (ID_TARIFF) ON DELETE CASCADE
);

CREATE UNIQUE INDEX XPKSALES ON SALES (  ID_SALES );

INSERT INTO TARIFFS (NAME, COST, DESCRIPTION) VALUES ('standart', 600, 'standart tariff');
INSERT INTO TARIFFS (NAME, COST, DESCRIPTION) VALUES ('standart2', 700, 'standart tariff');
INSERT INTO TARIFFS (NAME, COST, DESCRIPTION) VALUES ('standart3', 800, 'standart tariff');


INSERT INTO DISCOUNTS (AMOUNT, TIME_IN_COMPANY, DESCRIPTION) VALUES (100, 1, 'DESCRIPTION1');
INSERT INTO DISCOUNTS (AMOUNT, TIME_IN_COMPANY, DESCRIPTION) VALUES (200, 2, 'DESCRIPTION2');
INSERT INTO DISCOUNTS (AMOUNT, TIME_IN_COMPANY, DESCRIPTION) VALUES (300, 3, 'DESCRIPTION3');
